# Copyright 2024 Vladislav Aleinik

# Compilation flags:
CFLAGS=\
	-O2                          \
	-Wall                        \
	-Werror                      \
	-Wformat-security            \
	-Wignored-qualifiers         \
	-Winit-self                  \
	-Wswitch-default             \
	-Wfloat-equal                \
	-Wpointer-arith              \
	-Wtype-limits                \
	-Wempty-body                 \
	-Wno-logical-op              \
	-Wstrict-prototypes          \
	-Wold-style-declaration      \
	-Wold-style-definition       \
	-Wmissing-parameter-type     \
	-Wmissing-field-initializers \
	-Wnested-externs             \
	-Wno-pointer-sign            \
	-Wno-unused-result           \
	-std=gnu99                   \
	-lm

build/sort: sort.c
	@mkdir -p build
	@$(CC) sort.c ${CFLAGS} -o build/sort

run: build/sort
	@./build/sort

.PHONY: run

# Подключаем тестовую инфраструктуру.
PROGRAM=sort
PROGRAM_NAME=09_sort_lines
TESTS = 00

include ../../homework/common.mk
